title: "Aniruddhan Ganesaraman"
google_site_verification: "xXvU2nEgaD7Qp4ZdLhvH4zkLQuG3-PYMcAJoHgOVvQ0"
email: anigr@unc.edu
description: "PhD Student in Statistics and Operations Research at UNC Chapel Hill. "
url: "https://AniruddhanG.github.io"
baseurl: ""
github_username: AniruddhanG
minimal_mistakes_skin: mint      # try: air, dark, contrast, plum, sunrise

search: true
search_full_content: true
search_provider: lunr
lunr:
  search_within_pages: true
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: America/New_York

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "Aniruddhan Ganesaraman"
  avatar: "/assets/images/avatar.jpg"
  bio: "PhD Student in Statistics & Operations Research, UNC Chapel Hill."
  location: "Chapel Hill, NC, USA"
  email: anigr@unc.edu
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/AniruddhanG"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/aniruddhan-ganesaraman"

footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:anigr@unc.edu"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/AniruddhanG"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/aniruddhan-ganesaraman"

feed:
  disable: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      search: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/